# 
# docker-compose.yml — определяет сервисы для разработки и тестирования.

# Что нужно сделать:
#   - Настроить сервисы для:
#       - PostgreSQL (или MySQL) с начальной базой.
#       - Приложения Spring Boot (если нужно).
#   - Открыть нужные порты (например, 5432, 8080).
#   - Настроить volume для хранения данных БД.

version: "3.8"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bank
      POSTGRES_PASSWORD: bank
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bank -d bank"]
      interval: 5s
      timeout: 3s
      retries: 20

  adminer:
    image: adminer:4
    depends_on:
      - db
    ports:
      - "8081:8080"

volumes:
  db_data: {}